from PIL import Image, ImageDraw, ImageFont
import os
import asyncio
from typing import List, Dict
import requests
from io import BytesIO

class TopUsersImageGenerator:
    def __init__(self):
        self.width = 800
        self.height = 600
        self.bg_color = (15, 23, 42)  # Dark blue
        self.text_color = (255, 255, 255)  # White
        self.accent_color = (59, 130, 246)  # Blue
    
    async def create_top_users_image(self, users: List[Dict]) -> str:
        """Create top users image"""
        # Create image
        img = Image.new('RGB', (self.width, self.height), self.bg_color)
        draw = ImageDraw.Draw(img)
        
        try:
            # Try to use a nice font
            title_font = ImageFont.truetype("arial.ttf", 36)
            user_font = ImageFont.truetype("arial.ttf", 24)
            stats_font = ImageFont.truetype("arial.ttf", 18)
        except:
            # Fallback to default font
            title_font = ImageFont.load_default()
            user_font = ImageFont.load_default()
            stats_font = ImageFont.load_default()
        
        # Title
        title = "🏆 TOP ACTIVE USERS - SOCIAL BOUNTY"
        title_bbox = draw.textbbox((0, 0), title, font=title_font)
        title_width = title_bbox[2] - title_bbox[0]
        draw.text(
            ((self.width - title_width) // 2, 30),
            title,
            fill=self.accent_color,
            font=title_font
        )
        
        # Draw users
        y_offset = 100
        for i, user in enumerate(users[:10], 1):
            # Rank circle
            circle_x = 50
            circle_y = y_offset + 10
            draw.ellipse(
                [circle_x - 15, circle_y - 15, circle_x + 15, circle_y + 15],
                fill=self.accent_color
            )
            
            # Rank number
            rank_text = str(i)
            rank_bbox = draw.textbbox((0, 0), rank_text, font=user_font)
            rank_width = rank_bbox[2] - rank_bbox[0]
            draw.text(
                (circle_x - rank_width // 2, circle_y - 12),
                rank_text,
                fill=self.bg_color,
                font=user_font
            )
            
            # User name
            name = user.get('first_name', 'Unknown')[:20]
            draw.text((100, y_offset), name, fill=self.text_color, font=user_font)
            
            # Stats
            messages = user.get('message_count', 0)
            interactions = user.get('ai_interactions', 0)
            stats_text = f"Messages: {messages} | AI Chats: {interactions}"
            draw.text((100, y_offset + 25), stats_text, fill=(200, 200, 200), font=stats_font)
            
            y_offset += 50
        
        # Footer
        footer_text = "Generated by Social Bounty Support Bot"
        footer_bbox = draw.textbbox((0, 0), footer_text, font=stats_font)
        footer_width = footer_bbox[2] - footer_bbox[0]
        draw.text(
            ((self.width - footer_width) // 2, self.height - 40),
            footer_text,
            fill=(150, 150, 150),
            font=stats_font
        )
        
        # Save image
        filename = f"top_users_{asyncio.get_event_loop().time()}.png"
        img.save(filename)
        return filename
